"""add original_filename

Revision ID: 1daf4f80b188
Revises: 6c72888b60ea
Create Date: 2026-05-10 19:05:26.948396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1daf4f80b188'
down_revision = '6c72888b60ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False, server_default='', comment='Исходное имя файла от студента'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
