"""add template_validation_json

Revision ID: 6c72888b60ea
Revises: c39d5a3c79cf
Create Date: 2026-05-10 19:00:56.462006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c72888b60ea'
down_revision = 'c39d5a3c79cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_validation_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('template_validation_json')

    # ### end Alembic commands ###
