"""refactor models: ProjectCheck, drop Log, drop email

Revision ID: 6dd826cb5fb5
Revises: 1daf4f80b188
Create Date: 2026-05-10 19:13:35.035688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd826cb5fb5'
down_revision = '1daf4f80b188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safe_filename', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('final_report', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('file_type')
        batch_op.drop_column('processing_time')
        batch_op.drop_column('final_grade')
        batch_op.drop_column('template_validation_json')
        batch_op.drop_column('filename')
        batch_op.drop_column('report')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_size')
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=512), nullable=False))
        batch_op.add_column(sa.Column('report', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('template_validation_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('final_grade', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('processing_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=10), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('grade')
        batch_op.drop_column('final_report')
        batch_op.drop_column('safe_filename')

    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('check_id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
